server:
  port: 8080

spring:
  sql:
    init:
      platform: mysql
      mode: always
  datasource:
    url: jdbc:mysql://localhost:3306/cloud
    username: root # Database ID
    password: gik112233! # Database Password
    driver-class-name: com.mysql.cj.jdbc.Driver
#  datasource:
#    url: jdbc:mysql://my-database:3306/my-database
#    username: my-database # Database ID
#    password: gik112233! # Database Password
#    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        show_sql: true
        format_sql: true
        default_batch_fetch_size: 500
    defer-datasource-initialization: true
